---
# tasks file for patching RHEL-8/9, CentOS-8/9 and Rocky9
########################################################################################
#                                                                                      #
# --                                                                                   #
# Author: Joey Allen                                                                   #
#                                                                                      #
########################################################################################
#  Purpose: Playbook to perform 'dnf update' on selected hosts.                        #
#           All the packages with updates on the enabled repositories will be updated. #
#                                                                                      #
########################################################################################
### Supported OS: RHEL, CentOS and Rocky9                                              #
########################################################################################

- name: Tasks Patch Rocky9 RHEL9
  hosts: os_dnf
  become: true

  tasks:
    - name: Install updates on Rocky9 RHEL9
      ansible.builtin.dnf:
        name: '*'
        update_cache: true
        state: latest
      tags:
        - update-rhel8-9
...